apiVersion: apps/v1
kind: Deployment
metadata:
  name: desydeployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desyappsvc
      version: 'v1'
  template:
    metadata:
      labels:
        app: desyappsvc
        version: 'v1'
    spec:
      dnsPolicy: Default
      containers:
        - name: desyappsvc-app
          image: desycontainer.azurecr.us/desyappsvc:latest
          imagePullPolicy: Always
        restartPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: 'x-request-id,x-ot-span-context'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8181
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 120
