apiVersion: v1
kind: Service
metadata:
  name: desysvc
  namespace: default
  labels:
    app: desyappsvc
spec:
  selector:
    app: desyappsvc
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8181
    - name: https
      port: 443
      targetPort: 8181
