apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desy-app.fullname" . }}-deployment
  labels:
    app.kubernetes.io/name: {{ include "desy-app.name" . }}
    helm.sh/chart: {{ include "desy-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-desy
    app.kubernetes.io/managed-by: {{ .Release.Service }}-desy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "desy-app.name" . }}-desy
      app.kubernetes.io/instance: {{ .Release.Name }}-desy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "desy-app.name" . }}-desy
        app.kubernetes.io/instance: {{ .Release.Name }}-desy
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: JAVA_OPTS
          value: ' -Xmx256m -Xms256m'
        ports:
          - name: http
            containerPort: 8181
            protocol: TCP
        readinessProbe:
          httpGet:
            path: desy/management/health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: desy/management/health
            port: http
          initialDelaySeconds: 120
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
