apiVersion: v1
kind: Service
metadata:
  name: {{ include "desy-app.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "desy-app.name" . }}
    helm.sh/chart: {{ include "desy-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "desy-app.name" . }}-desy
    app.kubernetes.io/instance: {{ .Release.Name }}-desy
